// <auto-generated />
namespace ITRootsTask.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class userEdit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userEdit));
        
        string IMigrationMetadata.Id
        {
            get { return "202103060847192_userEdit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
